# Generated by Django 4.1.4 on 2023-08-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchactivity',
            old_name='slug',
            new_name='slugs',
        ),
    ]
