# Generated by Django 5.0.1 on 2024-03-11 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0002_rename_slug_churchactivity_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChurchActivity',
            new_name='ChurchActivityModel',
        ),
    ]
