# Generated by Django 5.0.1 on 2024-03-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0003_rename_churchactivity_churchactivitymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchactivitymodel',
            old_name='slugs',
            new_name='slug',
        ),
    ]
